// 合并自 meiguzuizhong-backup 和 meigulianghua3.6 的完整股票池
// 共 793 只美股

export type StockSector =
  | 'AI'
  | 'Semiconductor'
  | 'Bitcoin'
  | 'EV'
  | 'Quantum'
  | 'Storage'
  | 'RareEarth'
  | 'Cloud'
  | 'Fintech'
  | 'Energy'
  | 'Healthcare'
  | 'Retail'
  | 'Tech'
  | 'ETF'
  | 'Finance'
  | 'Defense'
  | 'Industrial'
  | 'Biotech'
  | 'Consumer'
  | 'Media'
  | 'China'
  | 'Robotics'
  | 'SpaceTech'
  | 'Other';

export interface StockInfo {
  symbol: string;
  name: string;
  sectors: StockSector[];
  marketCap: number; // 亿美元，0表示未知
}

export const STOCK_POOL: StockInfo[] = [
  // AI
  { symbol: 'NVDA', name: '英伟达', sectors: ['AI', 'Semiconductor'], marketCap: 33000 },
  { symbol: 'MSFT', name: '微软', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 31000 },
  { symbol: 'GOOGL', name: '谷歌A', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 21000 },
  { symbol: 'GOOG', name: '谷歌C', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 21000 },
  { symbol: 'META', name: 'Meta', sectors: ['AI', 'Tech', 'Media'], marketCap: 16000 },
  { symbol: 'AMZN', name: '亚马逊', sectors: ['AI', 'Cloud', 'Retail', 'Tech'], marketCap: 23000 },
  { symbol: 'AAPL', name: '苹果', sectors: ['AI', 'Tech'], marketCap: 35000 },
  { symbol: 'ORCL', name: '甲骨文', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 4800 },
  { symbol: 'CRM', name: 'Salesforce', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 3200 },
  { symbol: 'IBM', name: 'IBM', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 2300 },
  { symbol: 'PLTR', name: 'Palantir', sectors: ['AI', 'Tech'], marketCap: 2800 },
  { symbol: 'AI', name: 'C3.ai', sectors: ['AI', 'Tech'], marketCap: 40 },
  { symbol: 'BBAI', name: 'BigBear.ai', sectors: ['AI', 'Tech'], marketCap: 8 },
  { symbol: 'SOUN', name: 'SoundHound', sectors: ['AI', 'Tech'], marketCap: 50 },
  { symbol: 'PATH', name: 'UiPath', sectors: ['AI', 'Tech'], marketCap: 150 },
  { symbol: 'ADBE', name: 'Adobe', sectors: ['AI', 'Tech'], marketCap: 1800 },
  { symbol: 'NOW', name: 'ServiceNow', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 2200 },
  { symbol: 'GTLB', name: 'GitLab', sectors: ['AI', 'Tech'], marketCap: 100 },
  { symbol: 'APP', name: 'AppLovin', sectors: ['AI', 'Tech'], marketCap: 1500 },
  { symbol: 'RXRX', name: 'Recursion Pharma', sectors: ['AI', 'Biotech'], marketCap: 30 },
  { symbol: 'TEM', name: 'Tempus AI', sectors: ['AI', 'Healthcare'], marketCap: 60 },
  { symbol: 'DDOG', name: 'Datadog', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 500 },
  { symbol: 'SNOW', name: 'Snowflake', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 600 },
  { symbol: 'MDB', name: 'MongoDB', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 200 },
  { symbol: 'NET', name: 'Cloudflare', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 500 },
  { symbol: 'ZS', name: 'Zscaler', sectors: ['AI', 'Cloud', 'Tech'], marketCap: 400 },
  { symbol: 'CRWD', name: 'CrowdStrike', sectors: ['AI', 'Tech'], marketCap: 900 },
  { symbol: 'PANW', name: 'Palo Alto', sectors: ['AI', 'Tech'], marketCap: 1200 },
  { symbol: 'S', name: 'SentinelOne', sectors: ['AI', 'Tech'], marketCap: 200 },
  { symbol: 'DUOL', name: 'Duolingo', sectors: ['AI', 'Tech'], marketCap: 120 },
  { symbol: 'TTD', name: 'The Trade Desk', sectors: ['AI', 'Tech', 'Media'], marketCap: 600 },
  { symbol: 'RDDT', name: 'Reddit', sectors: ['AI', 'Tech', 'Media'], marketCap: 200 },
  { symbol: 'HIMS', name: 'Hims & Hers', sectors: ['AI', 'Healthcare'], marketCap: 60 },
  { symbol: 'CRWV', name: 'CoreWeave', sectors: ['AI', 'Cloud'], marketCap: 300 },
  { symbol: 'NBIS', name: 'Nebius Group', sectors: ['AI', 'Cloud'], marketCap: 50 },
  { symbol: 'DOMO', name: 'Domo', sectors: ['AI', 'Tech'], marketCap: 10 },
  { symbol: 'OPEN', name: 'Opendoor', sectors: ['AI', 'Tech'], marketCap: 10 },
  { symbol: 'AMD', name: 'AMD', sectors: ['AI', 'Semiconductor'], marketCap: 2500 },
  { symbol: 'AVGO', name: '博通', sectors: ['AI', 'Semiconductor'], marketCap: 9000 },
  { symbol: 'ARM', name: 'ARM Holdings', sectors: ['AI', 'Semiconductor'], marketCap: 1500 },
  { symbol: 'SMCI', name: '超微电脑', sectors: ['AI', 'Semiconductor'], marketCap: 300 },
  { symbol: 'ALAB', name: 'Astera Labs', sectors: ['AI', 'Semiconductor'], marketCap: 120 },
  { symbol: 'LAZR', name: 'Luminar Tech', sectors: ['AI', 'EV'], marketCap: 10 },
  // Tech
  { symbol: 'ANET', name: 'Arista Networks', sectors: ['Tech', 'AI'], marketCap: 1500 },
  { symbol: 'ACN', name: 'Accenture', sectors: ['Tech', 'AI'], marketCap: 2500 },
  { symbol: 'INTU', name: 'Intuit', sectors: ['Tech', 'Fintech'], marketCap: 1800 },
  { symbol: 'FTNT', name: 'Fortinet', sectors: ['Tech'], marketCap: 700 },
  { symbol: 'CDNS', name: 'Cadence Design', sectors: ['Tech', 'Semiconductor'], marketCap: 800 },
  { symbol: 'SNPS', name: 'Synopsys', sectors: ['Tech', 'Semiconductor'], marketCap: 800 },
  { symbol: 'ANSS', name: 'ANSYS', sectors: ['Tech'], marketCap: 400 },
  { symbol: 'CTSH', name: 'Cognizant', sectors: ['Tech'], marketCap: 400 },
  { symbol: 'EPAM', name: 'EPAM Systems', sectors: ['Tech'], marketCap: 200 },
  { symbol: 'GDDY', name: 'GoDaddy', sectors: ['Tech'], marketCap: 300 },
  { symbol: 'LITE', name: 'Lumentum', sectors: ['Tech', 'AI'], marketCap: 50 },
  { symbol: 'ABNB', name: 'Airbnb', sectors: ['Tech', 'Consumer'], marketCap: 1000 },
  { symbol: 'BKNG', name: 'Booking Holdings', sectors: ['Tech', 'Consumer'], marketCap: 2000 },
  { symbol: 'EXPE', name: 'Expedia', sectors: ['Tech', 'Consumer'], marketCap: 300 },
  { symbol: 'DASH', name: 'DoorDash', sectors: ['Tech', 'Retail'], marketCap: 600 },
  { symbol: 'UBER', name: 'Uber', sectors: ['Tech', 'EV'], marketCap: 2000 },
  { symbol: 'LYFT', name: 'Lyft', sectors: ['Tech', 'EV'], marketCap: 100 },
  { symbol: 'Z', name: 'Zillow', sectors: ['Tech', 'Retail'], marketCap: 200 },
  { symbol: 'RDFN', name: 'Redfin', sectors: ['Tech', 'Retail'], marketCap: 10 },
  { symbol: 'VZ', name: '威瑞森', sectors: ['Tech'], marketCap: 1800 },
  { symbol: 'T', name: 'AT&T', sectors: ['Tech'], marketCap: 1500 },
  { symbol: 'TMUS', name: 'T-Mobile', sectors: ['Tech'], marketCap: 2500 },
  { symbol: 'LUMN', name: 'Lumen Technologies', sectors: ['Tech'], marketCap: 20 },
  { symbol: 'CSCO', name: '思科', sectors: ['Tech'], marketCap: 2500 },
  { symbol: 'HPE', name: '惠普企业', sectors: ['Tech'], marketCap: 300 },
  { symbol: 'DELL', name: '戴尔', sectors: ['Tech', 'AI'], marketCap: 700 },
  { symbol: 'VRSN', name: 'VeriSign', sectors: ['Tech'], marketCap: 300 },
  { symbol: 'DXYZ', name: 'Destiny Tech100', sectors: ['Tech', 'ETF'], marketCap: 10 },
  { symbol: 'NMAX', name: 'NMAX', sectors: ['Tech'], marketCap: 5 },
  { symbol: 'TRIP', name: 'TripAdvisor', sectors: ['Tech', 'Consumer'], marketCap: 20 },
  { symbol: 'ADSK', name: 'Autodesk', sectors: ['Tech'], marketCap: 600 },
  { symbol: 'VRSK', name: 'Verisk Analytics', sectors: ['Tech', 'Finance'], marketCap: 400 },
  { symbol: 'IT', name: 'Gartner', sectors: ['Tech'], marketCap: 300 },
  { symbol: 'CSGP', name: 'CoStar Group', sectors: ['Tech', 'Other'], marketCap: 300 },
  { symbol: 'TRMB', name: 'Trimble', sectors: ['Tech', 'Industrial'], marketCap: 200 },
  { symbol: 'MANH', name: 'Manhattan Associates', sectors: ['Tech', 'Cloud'], marketCap: 300 },
  { symbol: 'TYL', name: 'Tyler Technologies', sectors: ['Tech', 'Cloud'], marketCap: 200 },
  { symbol: 'GWRE', name: 'Guidewire Software', sectors: ['Tech', 'Cloud'], marketCap: 100 },
  { symbol: 'PCOR', name: 'Procore Technologies', sectors: ['Tech', 'Cloud'], marketCap: 100 },
  { symbol: 'AZPN', name: 'Aspen Technology', sectors: ['Tech', 'Industrial'], marketCap: 100 },
  { symbol: 'APPS', name: 'APPS', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'POET', name: 'POET', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'CMCSA', name: 'CMCSA', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'ATVI', name: 'ATVI', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'ADP', name: 'ADP', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'PAYX', name: 'PAYX', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'TEL', name: 'TEL', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'APH', name: 'APH', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'KEYS', name: 'KEYS', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'SPLK', name: 'SPLK', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'TWTR', name: 'TWTR', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'FICO', name: 'FICO', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'AKAM', name: 'AKAM', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'JNPR', name: 'JNPR', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'FFIV', name: 'FFIV', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'NTCT', name: 'NTCT', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'RNG', name: 'RNG', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'DOCU', name: 'DOCU', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'BOX', name: 'BOX', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'DBX', name: 'DBX', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'COUP', name: 'COUP', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'SMAR', name: 'SMAR', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'ROKU', name: 'ROKU', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'CPNG', name: 'CPNG', sectors: ['Tech', 'Retail'], marketCap: 0 },
  { symbol: 'SE', name: 'SE', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'GRAB', name: 'GRAB', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'DIDI', name: 'DIDI', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'YELP', name: 'YELP', sectors: ['Tech'], marketCap: 0 },
  { symbol: 'GRUB', name: 'GRUB', sectors: ['Tech'], marketCap: 0 },
  // Cloud
  { symbol: 'CIEN', name: 'Ciena', sectors: ['Cloud', 'Tech'], marketCap: 100 },
  { symbol: 'SAP', name: 'SAP', sectors: ['Cloud', 'Tech'], marketCap: 3000 },
  { symbol: 'WDAY', name: 'Workday', sectors: ['Cloud', 'Tech'], marketCap: 600 },
  { symbol: 'VEEV', name: 'Veeva Systems', sectors: ['Cloud', 'Healthcare'], marketCap: 400 },
  { symbol: 'ZM', name: 'Zoom', sectors: ['Cloud', 'Tech'], marketCap: 200 },
  { symbol: 'TWLO', name: 'Twilio', sectors: ['Cloud', 'Tech'], marketCap: 200 },
  { symbol: 'HCP', name: 'HashiCorp', sectors: ['Cloud', 'Tech'], marketCap: 100 },
  { symbol: 'BILL', name: 'Bill.com', sectors: ['Cloud', 'Fintech'], marketCap: 100 },
  { symbol: 'HUBS', name: 'HubSpot', sectors: ['Cloud', 'Tech'], marketCap: 300 },
  { symbol: 'TEAM', name: 'Atlassian', sectors: ['Cloud', 'Tech'], marketCap: 600 },
  { symbol: 'ZI', name: 'ZoomInfo', sectors: ['Cloud', 'Tech'], marketCap: 50 },
  { symbol: 'DOCN', name: 'DigitalOcean', sectors: ['Cloud', 'Tech'], marketCap: 50 },
  { symbol: 'CFLT', name: 'Confluent', sectors: ['Cloud', 'Tech'], marketCap: 100 },
  { symbol: 'ESTC', name: 'Elastic', sectors: ['Cloud', 'Tech'], marketCap: 100 },
  { symbol: 'PD', name: 'PagerDuty', sectors: ['Cloud', 'Tech'], marketCap: 30 },
  { symbol: 'SUMO', name: 'Sumo Logic', sectors: ['Cloud', 'Tech'], marketCap: 10 },
  { symbol: 'APPN', name: 'Appian', sectors: ['Cloud', 'Tech'], marketCap: 20 },
  { symbol: 'NCNO', name: 'nCino', sectors: ['Cloud', 'Fintech'], marketCap: 30 },
  { symbol: 'SPSC', name: 'SPS Commerce', sectors: ['Cloud', 'Tech'], marketCap: 50 },
  { symbol: 'PCTY', name: 'Paylocity', sectors: ['Cloud', 'Fintech'], marketCap: 100 },
  { symbol: 'PAYC', name: 'Paycom', sectors: ['Cloud', 'Fintech'], marketCap: 100 },
  { symbol: 'EQIX', name: 'Equinix', sectors: ['Cloud', 'Other'], marketCap: 800 },
  { symbol: 'DLR', name: 'Digital Realty', sectors: ['Cloud', 'Other'], marketCap: 500 },
  { symbol: 'OKTA', name: 'OKTA', sectors: ['Cloud', 'Tech'], marketCap: 0 },
  { symbol: 'CYBR', name: 'CYBR', sectors: ['Cloud', 'Tech'], marketCap: 0 },
  // Semiconductor
  { symbol: 'TSM', name: '台积电', sectors: ['Semiconductor'], marketCap: 9500 },
  { symbol: 'ASML', name: 'ASML', sectors: ['Semiconductor'], marketCap: 3000 },
  { symbol: 'INTC', name: '英特尔', sectors: ['Semiconductor'], marketCap: 900 },
  { symbol: 'QCOM', name: '高通', sectors: ['Semiconductor'], marketCap: 1700 },
  { symbol: 'MU', name: '美光科技', sectors: ['Semiconductor', 'Storage'], marketCap: 1100 },
  { symbol: 'MRVL', name: 'Marvell', sectors: ['Semiconductor'], marketCap: 700 },
  { symbol: 'MCHP', name: 'Microchip', sectors: ['Semiconductor'], marketCap: 400 },
  { symbol: 'SOXL', name: '3x半导体ETF', sectors: ['Semiconductor', 'ETF'], marketCap: 100 },
  { symbol: 'TXN', name: '德州仪器', sectors: ['Semiconductor'], marketCap: 1700 },
  { symbol: 'ADI', name: 'Analog Devices', sectors: ['Semiconductor'], marketCap: 1000 },
  { symbol: 'NXPI', name: 'NXP半导体', sectors: ['Semiconductor'], marketCap: 500 },
  { symbol: 'KLAC', name: 'KLA', sectors: ['Semiconductor'], marketCap: 1000 },
  { symbol: 'LRCX', name: 'Lam Research', sectors: ['Semiconductor'], marketCap: 900 },
  { symbol: 'AMAT', name: 'Applied Materials', sectors: ['Semiconductor'], marketCap: 1400 },
  { symbol: 'COHR', name: 'Coherent', sectors: ['Semiconductor', 'AI'], marketCap: 200 },
  { symbol: 'ON', name: 'ON Semiconductor', sectors: ['Semiconductor'], marketCap: 700 },
  { symbol: 'SWKS', name: 'Skyworks', sectors: ['Semiconductor'], marketCap: 200 },
  { symbol: 'MPWR', name: 'Monolithic Power', sectors: ['Semiconductor'], marketCap: 400 },
  { symbol: 'ENTG', name: 'Entegris', sectors: ['Semiconductor'], marketCap: 200 },
  { symbol: 'ACLS', name: 'Axcelis Tech', sectors: ['Semiconductor'], marketCap: 30 },
  { symbol: 'ONTO', name: 'Onto Innovation', sectors: ['Semiconductor'], marketCap: 50 },
  { symbol: 'WOLF', name: 'Wolfspeed', sectors: ['Semiconductor'], marketCap: 10 },
  { symbol: 'NVTS', name: 'Navitas Semi', sectors: ['Semiconductor'], marketCap: 8 },
  { symbol: 'POWI', name: 'Power Integrations', sectors: ['Semiconductor'], marketCap: 20 },
  { symbol: 'IPGP', name: 'IPG Photonics', sectors: ['Semiconductor', 'Industrial'], marketCap: 100 },
  { symbol: 'FORM', name: 'FormFactor', sectors: ['Semiconductor'], marketCap: 20 },
  { symbol: 'CAMT', name: 'Camtek', sectors: ['Semiconductor'], marketCap: 30 },
  { symbol: 'AMKR', name: 'Amkor Technology', sectors: ['Semiconductor'], marketCap: 100 },
  { symbol: 'SITM', name: 'SiTime', sectors: ['Semiconductor'], marketCap: 20 },
  { symbol: 'ALGM', name: 'Allegro MicroSystems', sectors: ['Semiconductor'], marketCap: 30 },
  { symbol: 'CEVA', name: 'CEVA', sectors: ['Semiconductor'], marketCap: 0 },
  // Quantum
  { symbol: 'IONQ', name: 'IonQ', sectors: ['Quantum', 'Tech'], marketCap: 50 },
  { symbol: 'RGTI', name: 'Rigetti Computing', sectors: ['Quantum', 'Tech'], marketCap: 15 },
  { symbol: 'QUBT', name: 'Quantum Computing', sectors: ['Quantum', 'Tech'], marketCap: 8 },
  { symbol: 'QBTS', name: 'D-Wave Quantum', sectors: ['Quantum', 'Tech'], marketCap: 12 },
  { symbol: 'ARQQ', name: 'Arqit Quantum', sectors: ['Quantum', 'Tech'], marketCap: 5 },
  { symbol: 'OKLO', name: 'Oklo', sectors: ['Quantum', 'Energy'], marketCap: 30 },
  { symbol: 'SMR', name: 'NuScale Power', sectors: ['Quantum', 'Energy'], marketCap: 20 },
  { symbol: 'NNE', name: 'Nano Nuclear Energy', sectors: ['Quantum', 'Energy'], marketCap: 10 },
  { symbol: 'QTUM', name: 'QTUM', sectors: ['Quantum', 'Tech'], marketCap: 0 },
  // EV
  { symbol: 'QS', name: 'QuantumScape', sectors: ['EV', 'Quantum'], marketCap: 20 },
  { symbol: 'TSLA', name: '特斯拉', sectors: ['EV', 'AI', 'Robotics'], marketCap: 12000 },
  { symbol: 'TSLL', name: '2x特斯拉ETF', sectors: ['EV', 'ETF'], marketCap: 50 },
  { symbol: 'RIVN', name: 'Rivian', sectors: ['EV'], marketCap: 150 },
  { symbol: 'LCID', name: 'Lucid Group', sectors: ['EV'], marketCap: 30 },
  { symbol: 'NIO', name: '蔚来', sectors: ['EV', 'China'], marketCap: 80 },
  { symbol: 'LI', name: '理想汽车', sectors: ['EV', 'China'], marketCap: 200 },
  { symbol: 'XPEV', name: '小鹏汽车', sectors: ['EV', 'China'], marketCap: 100 },
  { symbol: 'GM', name: '通用汽车', sectors: ['EV', 'Industrial'], marketCap: 600 },
  { symbol: 'F', name: '福特', sectors: ['EV', 'Industrial'], marketCap: 500 },
  { symbol: 'CHPT', name: 'ChargePoint', sectors: ['EV'], marketCap: 10 },
  { symbol: 'BLNK', name: 'Blink Charging', sectors: ['EV'], marketCap: 5 },
  { symbol: 'AEVA', name: 'Aeva Tech', sectors: ['EV', 'AI'], marketCap: 5 },
  { symbol: 'AUR', name: 'Aurora Innovation', sectors: ['EV', 'AI', 'Robotics'], marketCap: 30 },
  { symbol: 'ACHR', name: 'Archer Aviation', sectors: ['EV', 'SpaceTech'], marketCap: 20 },
  { symbol: 'JOBY', name: 'Joby Aviation', sectors: ['EV', 'SpaceTech'], marketCap: 50 },
  { symbol: 'NKLA', name: 'Nikola', sectors: ['EV'], marketCap: 5 },
  { symbol: 'STLA', name: 'STLA', sectors: ['EV'], marketCap: 0 },
  { symbol: 'HMC', name: 'HMC', sectors: ['EV'], marketCap: 0 },
  { symbol: 'TM', name: 'TM', sectors: ['EV'], marketCap: 0 },
  // Bitcoin
  { symbol: 'MSTR', name: 'MicroStrategy', sectors: ['Bitcoin', 'Tech'], marketCap: 800 },
  { symbol: 'COIN', name: 'Coinbase', sectors: ['Bitcoin', 'Fintech'], marketCap: 700 },
  { symbol: 'MARA', name: 'Marathon Digital', sectors: ['Bitcoin'], marketCap: 60 },
  { symbol: 'RIOT', name: 'Riot Platforms', sectors: ['Bitcoin'], marketCap: 40 },
  { symbol: 'CLSK', name: 'CleanSpark', sectors: ['Bitcoin'], marketCap: 30 },
  { symbol: 'HUT', name: 'Hut 8 Mining', sectors: ['Bitcoin'], marketCap: 20 },
  { symbol: 'IREN', name: 'Iris Energy', sectors: ['Bitcoin'], marketCap: 20 },
  { symbol: 'CIFR', name: 'Cipher Mining', sectors: ['Bitcoin'], marketCap: 8 },
  { symbol: 'BTBT', name: 'Bit Digital', sectors: ['Bitcoin'], marketCap: 5 },
  { symbol: 'APLD', name: 'Applied Digital', sectors: ['Bitcoin', 'AI'], marketCap: 15 },
  { symbol: 'BITF', name: 'Bitfarms', sectors: ['Bitcoin'], marketCap: 10 },
  { symbol: 'HOOD', name: 'Robinhood', sectors: ['Bitcoin', 'Fintech'], marketCap: 400 },
  { symbol: 'SBET', name: 'SharpLink Gaming', sectors: ['Bitcoin'], marketCap: 3 },
  { symbol: 'BTC', name: 'BTC', sectors: ['Bitcoin'], marketCap: 0 },
  { symbol: 'BTQ', name: 'BTQ', sectors: ['Bitcoin'], marketCap: 0 },
  { symbol: 'WULF', name: 'WULF', sectors: ['Bitcoin'], marketCap: 0 },
  { symbol: 'CORZ', name: 'CORZ', sectors: ['Bitcoin'], marketCap: 0 },
  // Fintech
  { symbol: 'CRCL', name: 'Circle Internet', sectors: ['Fintech', 'Bitcoin'], marketCap: 50 },
  { symbol: 'PYPL', name: 'PayPal', sectors: ['Fintech'], marketCap: 800 },
  { symbol: 'SQ', name: 'Block', sectors: ['Fintech'], marketCap: 500 },
  { symbol: 'AFRM', name: 'Affirm', sectors: ['Fintech'], marketCap: 200 },
  { symbol: 'UPST', name: 'Upstart', sectors: ['Fintech', 'AI'], marketCap: 40 },
  { symbol: 'SOFI', name: 'SoFi', sectors: ['Fintech'], marketCap: 100 },
  { symbol: 'V', name: 'Visa', sectors: ['Fintech', 'Finance'], marketCap: 6000 },
  { symbol: 'MA', name: 'Mastercard', sectors: ['Fintech', 'Finance'], marketCap: 5000 },
  { symbol: 'AXP', name: '美国运通', sectors: ['Fintech', 'Finance'], marketCap: 2000 },
  { symbol: 'FIS', name: 'Fidelity National Info', sectors: ['Fintech'], marketCap: 400 },
  { symbol: 'FI', name: 'Fiserv', sectors: ['Fintech'], marketCap: 1000 },
  { symbol: 'NDAQ', name: '纳斯达克', sectors: ['Fintech', 'Finance'], marketCap: 500 },
  { symbol: 'ICE', name: 'ICE', sectors: ['Fintech', 'Finance'], marketCap: 900 },
  { symbol: 'CME', name: 'CME Group', sectors: ['Fintech', 'Finance'], marketCap: 900 },
  { symbol: 'CVNA', name: 'Carvana', sectors: ['Fintech', 'Retail'], marketCap: 500 },
  { symbol: 'FUTU', name: '富途控股', sectors: ['Fintech', 'China'], marketCap: 100 },
  { symbol: 'IBKR', name: '盈透证券', sectors: ['Fintech', 'Finance'], marketCap: 300 },
  { symbol: 'MKTX', name: 'MarketAxess', sectors: ['Fintech', 'Finance'], marketCap: 100 },
  { symbol: 'BR', name: 'Broadridge', sectors: ['Fintech', 'Tech'], marketCap: 300 },
  { symbol: 'SSNC', name: 'SS&C Tech', sectors: ['Fintech', 'Tech'], marketCap: 200 },
  { symbol: 'WEX', name: 'WEX', sectors: ['Fintech'], marketCap: 100 },
  { symbol: 'LMND', name: 'Lemonade', sectors: ['Fintech', 'AI'], marketCap: 20 },
  { symbol: 'QFIN', name: '奇富科技', sectors: ['Fintech', 'China'], marketCap: 30 },
  { symbol: 'TIGR', name: '老虎证券', sectors: ['Fintech', 'China'], marketCap: 10 },
  { symbol: 'GDOT', name: 'Green Dot', sectors: ['Fintech'], marketCap: 10 },
  { symbol: 'FISV', name: 'FISV', sectors: ['Fintech'], marketCap: 0 },
  // Storage
  { symbol: 'WDC', name: 'Western Digital', sectors: ['Storage'], marketCap: 200 },
  { symbol: 'STX', name: 'Seagate', sectors: ['Storage'], marketCap: 200 },
  { symbol: 'NTAP', name: 'NetApp', sectors: ['Storage', 'Cloud'], marketCap: 300 },
  { symbol: 'PSTG', name: 'Pure Storage', sectors: ['Storage', 'Cloud'], marketCap: 200 },
  { symbol: 'QMCO', name: 'Quantum Corp', sectors: ['Storage'], marketCap: 3 },
  { symbol: 'SNDK', name: 'SNDK', sectors: ['Storage', 'Tech'], marketCap: 0 },
  // China
  { symbol: 'PONY', name: '小马智行', sectors: ['China', 'AI', 'EV'], marketCap: 50 },
  { symbol: 'HSAI', name: '禾赛科技', sectors: ['China', 'AI', 'EV'], marketCap: 10 },
  { symbol: 'BIDU', name: '百度', sectors: ['China', 'AI', 'Robotics'], marketCap: 500 },
  { symbol: 'BABA', name: '阿里巴巴', sectors: ['China', 'Cloud', 'Retail'], marketCap: 2500 },
  { symbol: 'PDD', name: '拼多多', sectors: ['China', 'Retail'], marketCap: 1500 },
  { symbol: 'JD', name: '京东', sectors: ['China', 'Retail'], marketCap: 500 },
  { symbol: 'BEKE', name: '贝壳', sectors: ['China', 'Retail'], marketCap: 100 },
  { symbol: 'TCOM', name: '携程', sectors: ['China', 'Consumer'], marketCap: 300 },
  { symbol: 'GDS', name: '万国数据', sectors: ['China', 'Cloud'], marketCap: 30 },
  { symbol: 'YINN', name: '3x中国ETF', sectors: ['China', 'ETF'], marketCap: 20 },
  // SpaceTech
  { symbol: 'RKLB', name: 'Rocket Lab', sectors: ['SpaceTech', 'Defense'], marketCap: 100 },
  { symbol: 'LUNR', name: 'Intuitive Machines', sectors: ['SpaceTech'], marketCap: 20 },
  { symbol: 'ASTS', name: 'AST SpaceMobile', sectors: ['SpaceTech', 'Tech'], marketCap: 60 },
  { symbol: 'IRDM', name: 'Iridium', sectors: ['SpaceTech', 'Tech'], marketCap: 50 },
  { symbol: 'VSAT', name: 'ViaSat', sectors: ['SpaceTech', 'Tech'], marketCap: 30 },
  { symbol: 'SPCE', name: 'Virgin Galactic', sectors: ['SpaceTech'], marketCap: 5 },
  // Defense
  { symbol: 'LMT', name: '洛克希德马丁', sectors: ['Defense'], marketCap: 1500 },
  { symbol: 'RTX', name: '雷神技术', sectors: ['Defense'], marketCap: 1800 },
  { symbol: 'NOC', name: '诺斯罗普格鲁曼', sectors: ['Defense'], marketCap: 700 },
  { symbol: 'GD', name: '通用动力', sectors: ['Defense'], marketCap: 800 },
  { symbol: 'BA', name: '波音', sectors: ['Defense', 'Industrial'], marketCap: 1200 },
  { symbol: 'LHX', name: 'L3Harris', sectors: ['Defense'], marketCap: 400 },
  { symbol: 'HII', name: 'Huntington Ingalls', sectors: ['Defense'], marketCap: 100 },
  { symbol: 'KTOS', name: 'Kratos Defense', sectors: ['Defense', 'AI'], marketCap: 50 },
  { symbol: 'AXON', name: 'Axon Enterprise', sectors: ['Defense', 'AI'], marketCap: 500 },
  { symbol: 'LDOS', name: 'Leidos', sectors: ['Defense', 'AI'], marketCap: 300 },
  { symbol: 'SAIC', name: 'SAIC', sectors: ['Defense', 'Tech'], marketCap: 200 },
  { symbol: 'BAH', name: 'Booz Allen', sectors: ['Defense', 'AI'], marketCap: 300 },
  { symbol: 'CACI', name: 'CACI International', sectors: ['Defense', 'Tech'], marketCap: 100 },
  { symbol: 'AVAV', name: 'AeroVironment', sectors: ['Defense', 'Robotics'], marketCap: 50 },
  { symbol: 'DRS', name: 'Leonardo DRS', sectors: ['Defense'], marketCap: 100 },
  { symbol: 'ITA', name: '航空航天ETF', sectors: ['Defense', 'ETF'], marketCap: 100 },
  { symbol: 'BWXT', name: 'BWX Technologies', sectors: ['Defense', 'Energy'], marketCap: 100 },
  // RareEarth
  { symbol: 'MP', name: 'MP Materials', sectors: ['RareEarth'], marketCap: 30 },
  { symbol: 'NEM', name: 'Newmont', sectors: ['RareEarth', 'Energy'], marketCap: 500 },
  { symbol: 'GLD', name: '黄金ETF', sectors: ['RareEarth', 'ETF'], marketCap: 700 },
  { symbol: 'GDX', name: '黄金矿业ETF', sectors: ['RareEarth', 'ETF'], marketCap: 200 },
  { symbol: 'GDXU', name: '3x黄金矿业ETF', sectors: ['RareEarth', 'ETF'], marketCap: 20 },
  { symbol: 'TMC', name: 'The Metals Company', sectors: ['RareEarth'], marketCap: 5 },
  { symbol: 'AA', name: 'Alcoa', sectors: ['RareEarth', 'Industrial'], marketCap: 50 },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sectors: ['RareEarth', 'Industrial'], marketCap: 600 },
  { symbol: 'VALE', name: '淡水河谷', sectors: ['RareEarth', 'Industrial'], marketCap: 500 },
  { symbol: 'RIO', name: '力拓', sectors: ['RareEarth', 'Industrial'], marketCap: 1000 },
  { symbol: 'BHP', name: '必和必拓', sectors: ['RareEarth', 'Industrial'], marketCap: 1200 },
  { symbol: 'SLV', name: '白银ETF', sectors: ['RareEarth', 'ETF'], marketCap: 200 },
  { symbol: 'GOLD', name: 'Barrick Gold', sectors: ['RareEarth'], marketCap: 400 },
  { symbol: 'AEM', name: 'Agnico Eagle', sectors: ['RareEarth'], marketCap: 300 },
  { symbol: 'WPM', name: 'Wheaton Precious', sectors: ['RareEarth'], marketCap: 300 },
  { symbol: 'PAAS', name: 'Pan American Silver', sectors: ['RareEarth'], marketCap: 100 },
  { symbol: 'CRML', name: 'Critical Metals', sectors: ['RareEarth'], marketCap: 3 },
  { symbol: 'ALB', name: 'Albemarle', sectors: ['RareEarth', 'EV'], marketCap: 100 },
  { symbol: 'REMX', name: 'REMX', sectors: ['RareEarth', 'ETF'], marketCap: 0 },
  { symbol: 'LIT', name: 'LIT', sectors: ['RareEarth', 'ETF'], marketCap: 0 },
  // ETF
  { symbol: 'AGQ', name: '2x白银ETF', sectors: ['ETF', 'RareEarth'], marketCap: 20 },
  { symbol: 'DPST', name: '3x银行ETF', sectors: ['ETF', 'Finance'], marketCap: 50 },
  { symbol: 'KRE', name: '地区银行ETF', sectors: ['ETF', 'Finance'], marketCap: 200 },
  { symbol: 'XLF', name: '金融板块ETF', sectors: ['ETF', 'Finance'], marketCap: 4000 },
  { symbol: 'SPY', name: '标普500ETF', sectors: ['ETF'], marketCap: 60000 },
  { symbol: 'QQQ', name: '纳斯达克100ETF', sectors: ['ETF'], marketCap: 30000 },
  { symbol: 'IWM', name: '罗素2000ETF', sectors: ['ETF'], marketCap: 8000 },
  { symbol: 'VOO', name: '先锋标普500', sectors: ['ETF'], marketCap: 50000 },
  { symbol: 'VGT', name: '先锋科技ETF', sectors: ['ETF'], marketCap: 7000 },
  { symbol: 'TQQQ', name: '3x纳斯达克ETF', sectors: ['ETF'], marketCap: 2000 },
  { symbol: 'SQQQ', name: '3x做空纳斯达克', sectors: ['ETF'], marketCap: 500 },
  { symbol: 'UVXY', name: 'VIX波动率ETF', sectors: ['ETF'], marketCap: 100 },
  { symbol: 'TLT', name: '20年期国债ETF', sectors: ['ETF'], marketCap: 5000 },
  { symbol: 'TMF', name: '3x国债ETF', sectors: ['ETF'], marketCap: 200 },
  { symbol: 'TNA', name: '3x小盘股ETF', sectors: ['ETF'], marketCap: 100 },
  { symbol: 'LAES', name: '2x半导体ETF', sectors: ['ETF', 'Semiconductor'], marketCap: 10 },
  { symbol: 'UVIX', name: '2x VIX ETF', sectors: ['ETF'], marketCap: 20 },
  { symbol: 'XLK', name: '科技板块ETF', sectors: ['ETF', 'Tech'], marketCap: 5000 },
  { symbol: 'XLE', name: '能源板块ETF', sectors: ['ETF', 'Energy'], marketCap: 3000 },
  { symbol: 'XLV', name: '医疗板块ETF', sectors: ['ETF', 'Healthcare'], marketCap: 3000 },
  { symbol: 'XLI', name: '工业板块ETF', sectors: ['ETF', 'Industrial'], marketCap: 2000 },
  { symbol: 'XLY', name: '可选消费ETF', sectors: ['ETF', 'Consumer'], marketCap: 2000 },
  { symbol: 'XLP', name: '必需消费ETF', sectors: ['ETF', 'Consumer'], marketCap: 1500 },
  { symbol: 'XLB', name: '材料板块ETF', sectors: ['ETF', 'RareEarth'], marketCap: 1000 },
  { symbol: 'ARKK', name: 'ARK创新ETF', sectors: ['ETF', 'AI'], marketCap: 1000 },
  { symbol: 'ARKG', name: 'ARK基因组ETF', sectors: ['ETF', 'Biotech'], marketCap: 200 },
  { symbol: 'ARKW', name: 'ARK互联网ETF', sectors: ['ETF', 'Tech'], marketCap: 200 },
  { symbol: 'NAIL', name: 'NAIL', sectors: ['ETF'], marketCap: 0 },
  // Energy
  { symbol: 'XOM', name: '埃克森美孚', sectors: ['Energy'], marketCap: 5000 },
  { symbol: 'CVX', name: '雪佛龙', sectors: ['Energy'], marketCap: 2800 },
  { symbol: 'COP', name: 'ConocoPhillips', sectors: ['Energy'], marketCap: 1500 },
  { symbol: 'OXY', name: 'Occidental', sectors: ['Energy'], marketCap: 500 },
  { symbol: 'DVN', name: 'Devon Energy', sectors: ['Energy'], marketCap: 200 },
  { symbol: 'USO', name: '原油ETF', sectors: ['Energy', 'ETF'], marketCap: 50 },
  { symbol: 'VRT', name: 'Vertiv', sectors: ['Energy', 'AI'], marketCap: 500 },
  { symbol: 'VST', name: 'Vistra', sectors: ['Energy'], marketCap: 400 },
  { symbol: 'AES', name: 'AES Corp', sectors: ['Energy'], marketCap: 100 },
  { symbol: 'NEE', name: 'NextEra Energy', sectors: ['Energy'], marketCap: 1600 },
  { symbol: 'CEG', name: 'Constellation Energy', sectors: ['Energy'], marketCap: 800 },
  { symbol: 'FSLR', name: 'First Solar', sectors: ['Energy'], marketCap: 200 },
  { symbol: 'ENPH', name: 'Enphase Energy', sectors: ['Energy'], marketCap: 100 },
  { symbol: 'SLB', name: '斯伦贝谢', sectors: ['Energy'], marketCap: 800 },
  { symbol: 'HAL', name: '哈里伯顿', sectors: ['Energy'], marketCap: 400 },
  { symbol: 'BKR', name: 'Baker Hughes', sectors: ['Energy'], marketCap: 400 },
  { symbol: 'MPC', name: 'Marathon Petroleum', sectors: ['Energy'], marketCap: 700 },
  { symbol: 'VLO', name: 'Valero Energy', sectors: ['Energy'], marketCap: 500 },
  { symbol: 'PSX', name: 'Phillips 66', sectors: ['Energy'], marketCap: 500 },
  { symbol: 'PBR', name: '巴西石油', sectors: ['Energy'], marketCap: 800 },
  { symbol: 'BP', name: '英国石油', sectors: ['Energy'], marketCap: 1000 },
  { symbol: 'SHEL', name: '壳牌', sectors: ['Energy'], marketCap: 2000 },
  { symbol: 'TTE', name: '道达尔', sectors: ['Energy'], marketCap: 1500 },
  { symbol: 'LBRT', name: 'Liberty Energy', sectors: ['Energy'], marketCap: 20 },
  { symbol: 'D', name: 'Dominion Energy', sectors: ['Energy'], marketCap: 500 },
  { symbol: 'SO', name: 'Southern Company', sectors: ['Energy'], marketCap: 900 },
  { symbol: 'DUK', name: 'Duke Energy', sectors: ['Energy'], marketCap: 900 },
  { symbol: 'EXC', name: 'Exelon', sectors: ['Energy'], marketCap: 400 },
  { symbol: 'PCG', name: 'PG&E', sectors: ['Energy'], marketCap: 300 },
  { symbol: 'ETR', name: 'Entergy', sectors: ['Energy'], marketCap: 300 },
  { symbol: 'RUN', name: 'RUN', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'EOG', name: 'EOG', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'KMI', name: 'KMI', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'WMB', name: 'WMB', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'OKE', name: 'OKE', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'LNG', name: 'LNG', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'TRGP', name: 'TRGP', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'ET', name: 'ET', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'EPD', name: 'EPD', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'FANG', name: 'FANG', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'HES', name: 'HES', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'MRO', name: 'MRO', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'APA', name: 'APA', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'NOV', name: 'NOV', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'FTI', name: 'FTI', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'AEP', name: 'AEP', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'XEL', name: 'XEL', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'ED', name: 'ED', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'WEC', name: 'WEC', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'ES', name: 'ES', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'AEE', name: 'AEE', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'CMS', name: 'CMS', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'DTE', name: 'DTE', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'PPL', name: 'PPL', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'FE', name: 'FE', sectors: ['Energy'], marketCap: 0 },
  { symbol: 'CNP', name: 'CNP', sectors: ['Energy'], marketCap: 0 },
  // Industrial
  { symbol: 'GE', name: '通用电气', sectors: ['Industrial', 'Energy'], marketCap: 2000 },
  { symbol: 'CAT', name: '卡特彼勒', sectors: ['Industrial'], marketCap: 2000 },
  { symbol: 'DE', name: '迪尔', sectors: ['Industrial'], marketCap: 1500 },
  { symbol: 'HON', name: '霍尼韦尔', sectors: ['Industrial', 'AI'], marketCap: 1500 },
  { symbol: 'MMM', name: '3M', sectors: ['Industrial'], marketCap: 700 },
  { symbol: 'EMR', name: 'Emerson Electric', sectors: ['Industrial'], marketCap: 600 },
  { symbol: 'ROK', name: 'Rockwell Auto', sectors: ['Industrial', 'Robotics'], marketCap: 300 },
  { symbol: 'PH', name: 'Parker Hannifin', sectors: ['Industrial'], marketCap: 800 },
  { symbol: 'ITW', name: 'Illinois Tool Works', sectors: ['Industrial'], marketCap: 700 },
  { symbol: 'UPS', name: 'UPS', sectors: ['Industrial'], marketCap: 1200 },
  { symbol: 'FDX', name: 'FedEx', sectors: ['Industrial'], marketCap: 700 },
  { symbol: 'GLW', name: 'Corning', sectors: ['Industrial', 'Tech'], marketCap: 400 },
  { symbol: 'UAL', name: '联合航空', sectors: ['Industrial'], marketCap: 300 },
  { symbol: 'DAL', name: '达美航空', sectors: ['Industrial'], marketCap: 400 },
  { symbol: 'AAL', name: '美国航空', sectors: ['Industrial'], marketCap: 100 },
  { symbol: 'LUV', name: '西南航空', sectors: ['Industrial'], marketCap: 200 },
  { symbol: 'CSX', name: 'CSX', sectors: ['Industrial'], marketCap: 700 },
  { symbol: 'UNP', name: '联合太平洋', sectors: ['Industrial'], marketCap: 1500 },
  { symbol: 'NSC', name: 'Norfolk Southern', sectors: ['Industrial'], marketCap: 600 },
  { symbol: 'GEV', name: 'GE Vernova', sectors: ['Industrial', 'Energy'], marketCap: 800 },
  { symbol: 'ETN', name: 'Eaton', sectors: ['Industrial'], marketCap: 1500 },
  { symbol: 'AME', name: 'AMETEK', sectors: ['Industrial'], marketCap: 500 },
  { symbol: 'IR', name: 'Ingersoll Rand', sectors: ['Industrial'], marketCap: 400 },
  { symbol: 'XYL', name: 'Xylem', sectors: ['Industrial'], marketCap: 300 },
  { symbol: 'GNRC', name: 'Generac', sectors: ['Industrial', 'Energy'], marketCap: 100 },
  { symbol: 'CARR', name: 'Carrier Global', sectors: ['Industrial'], marketCap: 600 },
  { symbol: 'OTIS', name: 'Otis Worldwide', sectors: ['Industrial'], marketCap: 400 },
  { symbol: 'TT', name: 'Trane Technologies', sectors: ['Industrial'], marketCap: 600 },
  { symbol: 'FAST', name: 'Fastenal', sectors: ['Industrial'], marketCap: 500 },
  { symbol: 'GWW', name: 'W.W. Grainger', sectors: ['Industrial'], marketCap: 500 },
  { symbol: 'MSI', name: 'Motorola Solutions', sectors: ['Industrial', 'Tech'], marketCap: 600 },
  { symbol: 'LIN', name: 'Linde', sectors: ['Industrial', 'RareEarth'], marketCap: 2000 },
  { symbol: 'APD', name: 'Air Products', sectors: ['Industrial', 'Energy'], marketCap: 600 },
  { symbol: 'ECL', name: 'Ecolab', sectors: ['Industrial'], marketCap: 600 },
  { symbol: 'PPG', name: 'PPG Industries', sectors: ['Industrial'], marketCap: 300 },
  { symbol: 'NUE', name: 'Nucor', sectors: ['Industrial', 'RareEarth'], marketCap: 300 },
  { symbol: 'STLD', name: 'Steel Dynamics', sectors: ['Industrial', 'RareEarth'], marketCap: 200 },
  { symbol: 'CF', name: 'CF Industries', sectors: ['Industrial', 'Energy'], marketCap: 100 },
  { symbol: 'MOS', name: 'Mosaic', sectors: ['Industrial', 'RareEarth'], marketCap: 100 },
  { symbol: 'CTVA', name: 'Corteva', sectors: ['Industrial'], marketCap: 400 },
  { symbol: 'FMC', name: 'FMC Corp', sectors: ['Industrial'], marketCap: 50 },
  // Finance
  { symbol: 'JPM', name: '摩根大通', sectors: ['Finance'], marketCap: 7000 },
  { symbol: 'BAC', name: '美国银行', sectors: ['Finance'], marketCap: 3500 },
  { symbol: 'WFC', name: '富国银行', sectors: ['Finance'], marketCap: 2500 },
  { symbol: 'GS', name: '高盛', sectors: ['Finance'], marketCap: 2000 },
  { symbol: 'MS', name: '摩根士丹利', sectors: ['Finance'], marketCap: 2000 },
  { symbol: 'C', name: '花旗集团', sectors: ['Finance'], marketCap: 1500 },
  { symbol: 'BLK', name: '贝莱德', sectors: ['Finance'], marketCap: 1500 },
  { symbol: 'SCHW', name: '嘉信理财', sectors: ['Finance', 'Fintech'], marketCap: 1500 },
  { symbol: 'MET', name: 'MetLife', sectors: ['Finance'], marketCap: 600 },
  { symbol: 'PRU', name: 'Prudential', sectors: ['Finance'], marketCap: 500 },
  { symbol: 'AFL', name: 'Aflac', sectors: ['Finance'], marketCap: 600 },
  { symbol: 'ALL', name: 'Allstate', sectors: ['Finance'], marketCap: 600 },
  { symbol: 'TRV', name: 'Travelers', sectors: ['Finance'], marketCap: 600 },
  { symbol: 'USB', name: '美国合众银行', sectors: ['Finance'], marketCap: 700 },
  { symbol: 'PNC', name: 'PNC Financial', sectors: ['Finance'], marketCap: 700 },
  { symbol: 'TFC', name: 'Truist Financial', sectors: ['Finance'], marketCap: 600 },
  { symbol: 'COF', name: 'Capital One', sectors: ['Finance', 'Fintech'], marketCap: 700 },
  { symbol: 'DFS', name: 'Discover Financial', sectors: ['Finance', 'Fintech'], marketCap: 400 },
  { symbol: 'SYF', name: 'Synchrony Financial', sectors: ['Finance', 'Fintech'], marketCap: 200 },
  { symbol: 'ALLY', name: 'Ally Financial', sectors: ['Finance', 'Fintech'], marketCap: 200 },
  { symbol: 'LPLA', name: 'LPL Financial', sectors: ['Finance'], marketCap: 300 },
  { symbol: 'FIG', name: 'Forge Global', sectors: ['Finance', 'Fintech'], marketCap: 10 },
  { symbol: 'SPGI', name: 'S&P Global', sectors: ['Finance', 'Tech'], marketCap: 1500 },
  { symbol: 'MSCI', name: 'MSCI', sectors: ['Finance', 'Tech'], marketCap: 500 },
  // Healthcare
  { symbol: 'LLY', name: '礼来', sectors: ['Healthcare'], marketCap: 7000 },
  { symbol: 'UNH', name: '联合健康', sectors: ['Healthcare'], marketCap: 5000 },
  { symbol: 'JNJ', name: '强生', sectors: ['Healthcare'], marketCap: 4000 },
  { symbol: 'ABBV', name: '艾伯维', sectors: ['Healthcare'], marketCap: 3500 },
  { symbol: 'MRK', name: '默克', sectors: ['Healthcare'], marketCap: 2800 },
  { symbol: 'PFE', name: '辉瑞', sectors: ['Healthcare'], marketCap: 1500 },
  { symbol: 'MRNA', name: 'Moderna', sectors: ['Healthcare', 'Biotech'], marketCap: 200 },
  { symbol: 'AMGN', name: '安进', sectors: ['Healthcare', 'Biotech'], marketCap: 1700 },
  { symbol: 'GILD', name: '吉利德', sectors: ['Healthcare', 'Biotech'], marketCap: 1200 },
  { symbol: 'BIIB', name: '百健', sectors: ['Healthcare', 'Biotech'], marketCap: 300 },
  { symbol: 'REGN', name: 'Regeneron', sectors: ['Healthcare', 'Biotech'], marketCap: 800 },
  { symbol: 'VRTX', name: 'Vertex Pharma', sectors: ['Healthcare', 'Biotech'], marketCap: 1200 },
  { symbol: 'ISRG', name: '直觉外科', sectors: ['Healthcare', 'Robotics'], marketCap: 2000 },
  { symbol: 'DXCM', name: 'DexCom', sectors: ['Healthcare'], marketCap: 300 },
  { symbol: 'ILMN', name: 'Illumina', sectors: ['Healthcare', 'Biotech'], marketCap: 200 },
  { symbol: 'BMY', name: '百时美施贵宝', sectors: ['Healthcare'], marketCap: 1200 },
  { symbol: 'NVO', name: '诺和诺德', sectors: ['Healthcare'], marketCap: 3500 },
  { symbol: 'CELH', name: 'Celsius Holdings', sectors: ['Healthcare', 'Consumer'], marketCap: 50 },
  { symbol: 'MDT', name: 'Medtronic', sectors: ['Healthcare'], marketCap: 1200 },
  { symbol: 'BSX', name: 'Boston Scientific', sectors: ['Healthcare'], marketCap: 1500 },
  { symbol: 'EW', name: 'Edwards Life', sectors: ['Healthcare'], marketCap: 400 },
  { symbol: 'SYK', name: 'Stryker', sectors: ['Healthcare'], marketCap: 1500 },
  { symbol: 'BDX', name: 'Becton Dickinson', sectors: ['Healthcare'], marketCap: 700 },
  { symbol: 'BAX', name: 'Baxter', sectors: ['Healthcare'], marketCap: 100 },
  { symbol: 'HOLX', name: 'Hologic', sectors: ['Healthcare'], marketCap: 200 },
  { symbol: 'CVS', name: 'CVS Health', sectors: ['Healthcare', 'Retail'], marketCap: 1000 },
  { symbol: 'CI', name: 'Cigna', sectors: ['Healthcare'], marketCap: 1000 },
  { symbol: 'HUM', name: 'Humana', sectors: ['Healthcare'], marketCap: 500 },
  { symbol: 'MOH', name: 'Molina Healthcare', sectors: ['Healthcare'], marketCap: 200 },
  { symbol: 'CNC', name: 'Centene', sectors: ['Healthcare'], marketCap: 500 },
  { symbol: 'MCK', name: 'McKesson', sectors: ['Healthcare'], marketCap: 800 },
  { symbol: 'ABC', name: 'AmerisourceBergen', sectors: ['Healthcare'], marketCap: 500 },
  { symbol: 'CAH', name: 'Cardinal Health', sectors: ['Healthcare'], marketCap: 300 },
  { symbol: 'TDOC', name: 'Teladoc', sectors: ['Healthcare', 'Tech'], marketCap: 20 },
  { symbol: 'ZBH', name: 'Zimmer Biomet', sectors: ['Healthcare'], marketCap: 200 },
  { symbol: 'GEHC', name: 'GE HealthCare', sectors: ['Healthcare', 'AI'], marketCap: 400 },
  { symbol: 'IQV', name: 'IQVIA', sectors: ['Healthcare', 'Tech'], marketCap: 400 },
  { symbol: 'CRL', name: 'Charles River Labs', sectors: ['Healthcare', 'Biotech'], marketCap: 100 },
  { symbol: 'PKI', name: 'PerkinElmer', sectors: ['Healthcare', 'Tech'], marketCap: 100 },
  { symbol: 'RMD', name: 'ResMed', sectors: ['Healthcare'], marketCap: 400 },
  { symbol: 'PODD', name: 'Insulet', sectors: ['Healthcare'], marketCap: 200 },
  { symbol: 'ALGN', name: 'Align Technology', sectors: ['Healthcare'], marketCap: 200 },
  { symbol: 'XRAY', name: 'Dentsply Sirona', sectors: ['Healthcare'], marketCap: 50 },
  { symbol: 'HAE', name: 'Haemonetics', sectors: ['Healthcare'], marketCap: 30 },
  { symbol: 'BNTX', name: 'BioNTech', sectors: ['Healthcare', 'Biotech'], marketCap: 300 },
  { symbol: 'ALNY', name: 'Alnylam', sectors: ['Healthcare', 'Biotech'], marketCap: 400 },
  { symbol: 'INCY', name: 'Incyte', sectors: ['Healthcare', 'Biotech'], marketCap: 200 },
  { symbol: 'EXAS', name: 'Exact Sciences', sectors: ['Healthcare', 'Biotech'], marketCap: 100 },
  { symbol: 'RARE', name: 'Ultragenyx', sectors: ['Healthcare', 'Biotech'], marketCap: 50 },
  { symbol: 'SAGE', name: 'Sage Therapeutics', sectors: ['Healthcare', 'Biotech'], marketCap: 10 },
  { symbol: 'MSOS', name: '大麻ETF', sectors: ['Healthcare', 'ETF'], marketCap: 20 },
  { symbol: 'WELL', name: 'Welltower', sectors: ['Healthcare', 'Other'], marketCap: 700 },
  { symbol: 'TMO', name: 'Thermo Fisher', sectors: ['Healthcare', 'Biotech'], marketCap: 2000 },
  { symbol: 'DHR', name: 'Danaher', sectors: ['Healthcare', 'Biotech'], marketCap: 1500 },
  { symbol: 'A', name: 'Agilent Tech', sectors: ['Healthcare', 'Tech'], marketCap: 300 },
  { symbol: 'WAT', name: 'Waters Corp', sectors: ['Healthcare', 'Tech'], marketCap: 200 },
  { symbol: 'MTD', name: 'Mettler-Toledo', sectors: ['Healthcare', 'Industrial'], marketCap: 200 },
  { symbol: 'IDXX', name: 'IDEXX Labs', sectors: ['Healthcare'], marketCap: 400 },
  { symbol: 'TECH', name: 'Bio-Techne', sectors: ['Healthcare', 'Biotech'], marketCap: 100 },
  { symbol: 'TLRY', name: 'Tilray', sectors: ['Healthcare', 'Consumer'], marketCap: 10 },
  { symbol: 'CGC', name: 'Canopy Growth', sectors: ['Healthcare', 'Consumer'], marketCap: 5 },
  { symbol: 'ACB', name: 'Aurora Cannabis', sectors: ['Healthcare', 'Consumer'], marketCap: 5 },
  { symbol: 'CRON', name: 'Cronos', sectors: ['Healthcare', 'Consumer'], marketCap: 10 },
  { symbol: 'ATAI', name: 'ATAI', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'ABT', name: 'ABT', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'DGX', name: 'DGX', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'LH', name: 'LH', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'ZTS', name: 'ZTS', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'ELV', name: 'ELV', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'VTRS', name: 'VTRS', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'COR', name: 'COR', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'SGEN', name: 'SGEN', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'JAZZ', name: 'JAZZ', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'UTHR', name: 'UTHR', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'BLUE', name: 'BLUE', sectors: ['Healthcare'], marketCap: 0 },
  { symbol: 'VERV', name: 'VERV', sectors: ['Healthcare'], marketCap: 0 },
  // Biotech
  { symbol: 'SRPT', name: 'Sarepta Therapeutics', sectors: ['Biotech'], marketCap: 100 },
  { symbol: 'BMRN', name: 'BioMarin', sectors: ['Biotech'], marketCap: 200 },
  { symbol: 'IONS', name: 'Ionis Pharma', sectors: ['Biotech'], marketCap: 100 },
  { symbol: 'NBIX', name: 'Neurocrine Bio', sectors: ['Biotech'], marketCap: 200 },
  { symbol: 'ARWR', name: 'Arrowhead Pharma', sectors: ['Biotech'], marketCap: 30 },
  { symbol: 'FOLD', name: 'Amicus Therapeutics', sectors: ['Biotech'], marketCap: 30 },
  { symbol: 'IMVT', name: 'Immunovant', sectors: ['Biotech'], marketCap: 30 },
  { symbol: 'NTLA', name: 'Intellia Therapeutics', sectors: ['Biotech'], marketCap: 20 },
  { symbol: 'BEAM', name: 'Beam Therapeutics', sectors: ['Biotech'], marketCap: 20 },
  { symbol: 'CRSP', name: 'CRISPR Therapeutics', sectors: ['Biotech'], marketCap: 50 },
  { symbol: 'EDIT', name: 'Editas Medicine', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'NVAX', name: 'Novavax', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'KYMR', name: 'Kymera Therapeutics', sectors: ['Biotech'], marketCap: 20 },
  { symbol: 'ARCT', name: 'Arctus Bio', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'PACB', name: 'Pacific Biosciences', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'SRRK', name: 'Scholar Rock', sectors: ['Biotech'], marketCap: 20 },
  { symbol: 'PTGX', name: 'Protagonist Therapeutics', sectors: ['Biotech'], marketCap: 20 },
  { symbol: 'RXDX', name: 'Turning Point Therapeutics', sectors: ['Biotech'], marketCap: 20 },
  { symbol: 'HALO', name: 'Halozyme', sectors: ['Biotech'], marketCap: 100 },
  { symbol: 'ACAD', name: 'ACADIA Pharma', sectors: ['Biotech'], marketCap: 50 },
  { symbol: 'NKTR', name: 'Nektar Therapeutics', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'FATE', name: 'Fate Therapeutics', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'TWST', name: 'Twist Bioscience', sectors: ['Biotech'], marketCap: 10 },
  { symbol: 'RCUS', name: 'Arcus Biosciences', sectors: ['Biotech'], marketCap: 20 },
  // Retail
  { symbol: 'WMT', name: '沃尔玛', sectors: ['Retail'], marketCap: 8000 },
  { symbol: 'COST', name: 'Costco', sectors: ['Retail'], marketCap: 4000 },
  { symbol: 'TGT', name: 'Target', sectors: ['Retail'], marketCap: 500 },
  { symbol: 'HD', name: '家得宝', sectors: ['Retail'], marketCap: 4000 },
  { symbol: 'NKE', name: '耐克', sectors: ['Retail', 'Consumer'], marketCap: 1200 },
  { symbol: 'LULU', name: 'lululemon', sectors: ['Retail', 'Consumer'], marketCap: 400 },
  { symbol: 'SHOP', name: 'Shopify', sectors: ['Retail', 'Tech'], marketCap: 1500 },
  { symbol: 'MELI', name: 'MercadoLibre', sectors: ['Retail', 'Fintech'], marketCap: 1000 },
  { symbol: 'ULTA', name: 'Ulta Beauty', sectors: ['Retail', 'Consumer'], marketCap: 200 },
  { symbol: 'ETSY', name: 'Etsy', sectors: ['Retail', 'Tech'], marketCap: 100 },
  { symbol: 'EBAY', name: 'eBay', sectors: ['Retail', 'Tech'], marketCap: 300 },
  { symbol: 'W', name: 'Wayfair', sectors: ['Retail', 'Tech'], marketCap: 100 },
  { symbol: 'RERE', name: '爱回收', sectors: ['Retail', 'China'], marketCap: 5 },
  { symbol: 'SPG', name: 'Simon Property', sectors: ['Retail', 'Other'], marketCap: 600 },
  { symbol: 'LOW', name: 'LOW', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'TJX', name: 'TJX', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'ROST', name: 'ROST', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'DG', name: 'DG', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'DLTR', name: 'DLTR', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'ORLY', name: 'ORLY', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'AZO', name: 'AZO', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'AAP', name: 'AAP', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'TSCO', name: 'TSCO', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'BBY', name: 'BBY', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'GPS', name: 'GPS', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'ANF', name: 'ANF', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'AEO', name: 'AEO', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'URBN', name: 'URBN', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'RL', name: 'RL', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'PVH', name: 'PVH', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'TPR', name: 'TPR', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'CPRI', name: 'CPRI', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'VFC', name: 'VFC', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'UAA', name: 'UAA', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'CROX', name: 'CROX', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'DECK', name: 'DECK', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'SKX', name: 'SKX', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'FL', name: 'FL', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'DKS', name: 'DKS', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'CHWY', name: 'CHWY', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'PETS', name: 'PETS', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'DPZ', name: 'DPZ', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'WEN', name: 'WEN', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'SHAK', name: 'SHAK', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'WING', name: 'WING', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'BLMN', name: 'BLMN', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'DRI', name: 'DRI', sectors: ['Retail'], marketCap: 0 },
  { symbol: 'EAT', name: 'EAT', sectors: ['Retail'], marketCap: 0 },
  // Consumer
  { symbol: 'KO', name: '可口可乐', sectors: ['Consumer'], marketCap: 3000 },
  { symbol: 'PEP', name: '百事可乐', sectors: ['Consumer'], marketCap: 2500 },
  { symbol: 'MCD', name: '麦当劳', sectors: ['Consumer'], marketCap: 2000 },
  { symbol: 'SBUX', name: '星巴克', sectors: ['Consumer'], marketCap: 1000 },
  { symbol: 'KHC', name: '卡夫亨氏', sectors: ['Consumer'], marketCap: 300 },
  { symbol: 'PM', name: '菲利普莫里斯', sectors: ['Consumer'], marketCap: 2500 },
  { symbol: 'PG', name: '宝洁', sectors: ['Consumer'], marketCap: 4000 },
  { symbol: 'CL', name: '高露洁', sectors: ['Consumer'], marketCap: 600 },
  { symbol: 'KMB', name: 'Kimberly-Clark', sectors: ['Consumer'], marketCap: 400 },
  { symbol: 'CLX', name: 'Clorox', sectors: ['Consumer'], marketCap: 200 },
  { symbol: 'EL', name: '雅诗兰黛', sectors: ['Consumer'], marketCap: 300 },
  { symbol: 'PTON', name: 'Peloton', sectors: ['Consumer', 'Tech'], marketCap: 20 },
  { symbol: 'MGM', name: 'MGM Resorts', sectors: ['Consumer'], marketCap: 200 },
  { symbol: 'WYNN', name: 'Wynn Resorts', sectors: ['Consumer'], marketCap: 100 },
  { symbol: 'LVS', name: '拉斯维加斯金沙', sectors: ['Consumer'], marketCap: 400 },
  { symbol: 'MO', name: 'Altria', sectors: ['Consumer'], marketCap: 1000 },
  { symbol: 'STZ', name: 'Constellation Brands', sectors: ['Consumer'], marketCap: 400 },
  { symbol: 'TAP', name: 'Molson Coors', sectors: ['Consumer'], marketCap: 100 },
  { symbol: 'GIS', name: 'General Mills', sectors: ['Consumer'], marketCap: 400 },
  { symbol: 'K', name: 'Kellanova', sectors: ['Consumer'], marketCap: 200 },
  { symbol: 'CPB', name: 'Campbell Soup', sectors: ['Consumer'], marketCap: 100 },
  { symbol: 'HRL', name: 'Hormel Foods', sectors: ['Consumer'], marketCap: 100 },
  { symbol: 'SJM', name: 'J.M. Smucker', sectors: ['Consumer'], marketCap: 100 },
  { symbol: 'MKC', name: 'McCormick', sectors: ['Consumer'], marketCap: 200 },
  { symbol: 'HSY', name: 'Hershey', sectors: ['Consumer'], marketCap: 300 },
  { symbol: 'MDLZ', name: 'Mondelez', sectors: ['Consumer'], marketCap: 800 },
  { symbol: 'SHW', name: 'Sherwin-Williams', sectors: ['Consumer', 'Industrial'], marketCap: 900 },
  { symbol: 'CHD', name: 'Church & Dwight', sectors: ['Consumer'], marketCap: 300 },
  { symbol: 'PZZA', name: '棒约翰', sectors: ['Consumer'], marketCap: 10 },
  { symbol: 'YUM', name: 'Yum! Brands', sectors: ['Consumer'], marketCap: 400 },
  { symbol: 'QSR', name: 'Restaurant Brands', sectors: ['Consumer'], marketCap: 300 },
  { symbol: 'CMG', name: 'Chipotle', sectors: ['Consumer'], marketCap: 900 },
  { symbol: 'JACK', name: 'Jack in the Box', sectors: ['Consumer'], marketCap: 10 },
  { symbol: 'TXRH', name: 'Texas Roadhouse', sectors: ['Consumer'], marketCap: 100 },
  { symbol: 'DINE', name: 'Dine Brands', sectors: ['Consumer'], marketCap: 10 },
  { symbol: 'MAR', name: '万豪酒店', sectors: ['Consumer'], marketCap: 700 },
  { symbol: 'HLT', name: '希尔顿', sectors: ['Consumer'], marketCap: 600 },
  { symbol: 'H', name: '凯悦酒店', sectors: ['Consumer'], marketCap: 200 },
  { symbol: 'IHG', name: '洲际酒店', sectors: ['Consumer'], marketCap: 200 },
  { symbol: 'RCL', name: '皇家加勒比', sectors: ['Consumer'], marketCap: 500 },
  { symbol: 'CCL', name: '嘉年华邮轮', sectors: ['Consumer'], marketCap: 300 },
  { symbol: 'NCLH', name: '挪威邮轮', sectors: ['Consumer'], marketCap: 100 },
  // Media
  { symbol: 'DKNG', name: 'DraftKings', sectors: ['Media', 'Tech'], marketCap: 200 },
  { symbol: 'PENN', name: 'Penn Entertainment', sectors: ['Media', 'Consumer'], marketCap: 50 },
  { symbol: 'NFLX', name: 'Netflix', sectors: ['Media', 'Tech'], marketCap: 4000 },
  { symbol: 'DIS', name: '迪士尼', sectors: ['Media', 'Consumer'], marketCap: 2000 },
  { symbol: 'SPOT', name: 'Spotify', sectors: ['Media', 'Tech'], marketCap: 1000 },
  { symbol: 'SNAP', name: 'Snap', sectors: ['Media', 'Tech'], marketCap: 200 },
  { symbol: 'RBLX', name: 'Roblox', sectors: ['Media', 'Tech'], marketCap: 300 },
  { symbol: 'U', name: 'Unity', sectors: ['Media', 'Tech'], marketCap: 100 },
  { symbol: 'TTWO', name: 'Take-Two', sectors: ['Media', 'Tech'], marketCap: 300 },
  { symbol: 'EA', name: 'Electronic Arts', sectors: ['Media', 'Tech'], marketCap: 400 },
  { symbol: 'PINS', name: 'Pinterest', sectors: ['Media', 'Tech'], marketCap: 200 },
  { symbol: 'MTCH', name: 'Match Group', sectors: ['Media', 'Tech'], marketCap: 100 },
  { symbol: 'BMBL', name: 'Bumble', sectors: ['Media', 'Tech'], marketCap: 20 },
  { symbol: 'SIRI', name: 'Sirius XM', sectors: ['Media', 'Tech'], marketCap: 100 },
  { symbol: 'GME', name: 'GameStop', sectors: ['Media', 'Retail'], marketCap: 20 },
  { symbol: 'BILI', name: '哔哩哔哩', sectors: ['Media', 'China'], marketCap: 50 },
  { symbol: 'PARA', name: 'Paramount', sectors: ['Media'], marketCap: 100 },
  { symbol: 'WBD', name: 'Warner Bros Discovery', sectors: ['Media'], marketCap: 200 },
  { symbol: 'FOXA', name: 'Fox Corp A', sectors: ['Media'], marketCap: 200 },
  { symbol: 'NYT', name: 'New York Times', sectors: ['Media'], marketCap: 100 },
  { symbol: 'IAC', name: 'IAC', sectors: ['Media', 'Tech'], marketCap: 50 },
  { symbol: 'NTES', name: '网易', sectors: ['Media', 'China'], marketCap: 500 },
  { symbol: 'TME', name: '腾讯音乐', sectors: ['Media', 'China'], marketCap: 100 },
  { symbol: 'IQ', name: '爱奇艺', sectors: ['Media', 'China'], marketCap: 30 },
  { symbol: 'HUYA', name: '虎牙', sectors: ['Media', 'China'], marketCap: 10 },
  { symbol: 'DOYU', name: '斗鱼', sectors: ['Media', 'China'], marketCap: 5 },
  { symbol: 'DISH', name: 'DISH Network', sectors: ['Media', 'Tech'], marketCap: 20 },
  { symbol: 'MSGE', name: 'MSG Entertainment', sectors: ['Media', 'Consumer'], marketCap: 30 },
  // Robotics
  { symbol: 'ABB', name: 'ABB', sectors: ['Robotics', 'Industrial'], marketCap: 1000 },
  { symbol: 'FANUY', name: '发那科', sectors: ['Robotics', 'Industrial'], marketCap: 400 },
  { symbol: 'IRBT', name: 'iRobot', sectors: ['Robotics'], marketCap: 10 },
  { symbol: 'SERV', name: 'Serve Robotics', sectors: ['Robotics', 'AI'], marketCap: 10 },
  { symbol: 'ONDS', name: 'Ondas Holdings', sectors: ['Robotics', 'Defense'], marketCap: 3 },
  // Other
  { symbol: 'AMT', name: 'American Tower', sectors: ['Other'], marketCap: 1000 },
  { symbol: 'PLD', name: 'Prologis', sectors: ['Other'], marketCap: 1000 },
  { symbol: 'CCI', name: 'Crown Castle', sectors: ['Other'], marketCap: 500 },
  { symbol: 'O', name: 'Realty Income', sectors: ['Other'], marketCap: 500 },
  { symbol: 'AVB', name: 'AvalonBay', sectors: ['Other'], marketCap: 300 },
  { symbol: 'EQR', name: 'Equity Residential', sectors: ['Other'], marketCap: 300 },
  { symbol: 'OPEX', name: 'OPEX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DJT', name: 'DJT', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DJTU', name: 'DJTU', sectors: ['Other'], marketCap: 0 },
  { symbol: 'FMCC', name: 'FMCC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'FNMA', name: 'FNMA', sectors: ['Other'], marketCap: 0 },
  { symbol: 'NVTX', name: 'NVTX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'ONDL', name: 'ONDL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TSNF', name: 'TSNF', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TSRS', name: 'TSRS', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TSES', name: 'TSES', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TSIC', name: 'TSIC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TSSD', name: 'TSSD', sectors: ['Other'], marketCap: 0 },
  { symbol: 'NXDR', name: 'NXDR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TGL', name: 'TGL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'SMX', name: 'SMX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'WRD', name: 'WRD', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BETR', name: 'BETR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'SNGX', name: 'SNGX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DGNX', name: 'DGNX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'APG', name: 'APG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'GRRR', name: 'GRRR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'UPSX', name: 'UPSX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CRCA', name: 'CRCA', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CWVX', name: 'CWVX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'OKLL', name: 'OKLL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'RGTX', name: 'RGTX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'RDTL', name: 'RDTL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AMPX', name: 'AMPX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BYND', name: 'BYND', sectors: ['Other'], marketCap: 0 },
  { symbol: 'MEME', name: 'MEME', sectors: ['Other'], marketCap: 0 },
  { symbol: 'USAR', name: 'USAR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'FIGR', name: 'FIGR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'GEMI', name: 'GEMI', sectors: ['Other'], marketCap: 0 },
  { symbol: 'ORBS', name: 'ORBS', sectors: ['Other'], marketCap: 0 },
  { symbol: 'OPAD', name: 'OPAD', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DUO', name: 'DUO', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BLSH', name: 'BLSH', sectors: ['Other'], marketCap: 0 },
  { symbol: 'VSCO', name: 'VSCO', sectors: ['Other'], marketCap: 0 },
  { symbol: 'IXHL', name: 'IXHL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'XRPT', name: 'XRPT', sectors: ['Other'], marketCap: 0 },
  { symbol: 'VOR', name: 'VOR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'ASST', name: 'ASST', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BMNR', name: 'BMNR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TRON', name: 'TRON', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AGIG', name: 'AGIG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'PSH', name: 'PSH', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AIRO', name: 'AIRO', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CHYM', name: 'CHYM', sectors: ['Other'], marketCap: 0 },
  { symbol: 'NAKA', name: 'NAKA', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BNS', name: 'BNS', sectors: ['Other'], marketCap: 0 },
  { symbol: 'RGC', name: 'RGC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BULL', name: 'BULL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'B', name: 'B', sectors: ['Other'], marketCap: 0 },
  { symbol: 'WKEY', name: 'WKEY', sectors: ['Other'], marketCap: 0 },
  { symbol: 'KITT', name: 'KITT', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CRNC', name: 'CRNC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'RR', name: 'RR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'XOVR', name: 'XOVR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'HOLO', name: 'HOLO', sectors: ['Other'], marketCap: 0 },
  { symbol: 'SES', name: 'SES', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AVDL', name: 'AVDL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'KC', name: 'KC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DOW', name: 'DOW', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DD', name: 'DD', sectors: ['Other'], marketCap: 0 },
  { symbol: 'EMN', name: 'EMN', sectors: ['Other'], marketCap: 0 },
  { symbol: 'MNST', name: 'MNST', sectors: ['Other'], marketCap: 0 },
  { symbol: 'VMC', name: 'VMC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'MLM', name: 'MLM', sectors: ['Other'], marketCap: 0 },
  { symbol: 'WM', name: 'WM', sectors: ['Other'], marketCap: 0 },
  { symbol: 'RSG', name: 'RSG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BK', name: 'BK', sectors: ['Other'], marketCap: 0 },
  { symbol: 'MCO', name: 'MCO', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AON', name: 'AON', sectors: ['Other'], marketCap: 0 },
  { symbol: 'MMC', name: 'MMC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AJG', name: 'AJG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CB', name: 'CB', sectors: ['Other'], marketCap: 0 },
  { symbol: 'PGR', name: 'PGR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AIG', name: 'AIG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'HIG', name: 'HIG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'DOV', name: 'DOV', sectors: ['Other'], marketCap: 0 },
  { symbol: 'IEX', name: 'IEX', sectors: ['Other'], marketCap: 0 },
  { symbol: 'FTV', name: 'FTV', sectors: ['Other'], marketCap: 0 },
  { symbol: 'PWR', name: 'PWR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'J', name: 'J', sectors: ['Other'], marketCap: 0 },
  { symbol: 'FLR', name: 'FLR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'KBR', name: 'KBR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CHRW', name: 'CHRW', sectors: ['Other'], marketCap: 0 },
  { symbol: 'JBHT', name: 'JBHT', sectors: ['Other'], marketCap: 0 },
  { symbol: 'ODFL', name: 'ODFL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'XPO', name: 'XPO', sectors: ['Other'], marketCap: 0 },
  { symbol: 'RS', name: 'RS', sectors: ['Other'], marketCap: 0 },
  { symbol: 'X', name: 'X', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CLF', name: 'CLF', sectors: ['Other'], marketCap: 0 },
  { symbol: 'MT', name: 'MT', sectors: ['Other'], marketCap: 0 },
  { symbol: 'PKG', name: 'PKG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'IP', name: 'IP', sectors: ['Other'], marketCap: 0 },
  { symbol: 'WRK', name: 'WRK', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AVY', name: 'AVY', sectors: ['Other'], marketCap: 0 },
  { symbol: 'SEE', name: 'SEE', sectors: ['Other'], marketCap: 0 },
  { symbol: 'BALL', name: 'BALL', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AMCR', name: 'AMCR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CCK', name: 'CCK', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CE', name: 'CE', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CAG', name: 'CAG', sectors: ['Other'], marketCap: 0 },
  { symbol: 'TSN', name: 'TSN', sectors: ['Other'], marketCap: 0 },
  { symbol: 'SAM', name: 'SAM', sectors: ['Other'], marketCap: 0 },
  { symbol: 'FIZZ', name: 'FIZZ', sectors: ['Other'], marketCap: 0 },
  { symbol: 'KDP', name: 'KDP', sectors: ['Other'], marketCap: 0 },
  { symbol: 'PSA', name: 'PSA', sectors: ['Other'], marketCap: 0 },
  { symbol: 'VTR', name: 'VTR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'SBAC', name: 'SBAC', sectors: ['Other'], marketCap: 0 },
  { symbol: 'INVH', name: 'INVH', sectors: ['Other'], marketCap: 0 },
  { symbol: 'EXR', name: 'EXR', sectors: ['Other'], marketCap: 0 },
  { symbol: 'CUBE', name: 'CUBE', sectors: ['Other'], marketCap: 0 },
  { symbol: 'LSI', name: 'LSI', sectors: ['Other'], marketCap: 0 },
  { symbol: 'AWK', name: 'AWK', sectors: ['Other'], marketCap: 0 },
];

// 去重（保留第一次出现）
const _seen = new Set<string>();
export const UNIQUE_STOCK_POOL: StockInfo[] = STOCK_POOL.filter(s => {
  if (_seen.has(s.symbol)) return false;
  _seen.add(s.symbol);
  return true;
});

/**
 * 市值筛选阈值（亿美元）
 */
export const MARKET_CAP_FILTERS = {
  all: 0,
  '1b': 10,      // 10亿美元
  '10b': 100,    // 100亿美元
  '50b': 500,    // 500亿美元
  '100b': 1000,  // 1000亿美元
  '500b': 5000,  // 5000亿美元
} as const;

export type MarketCapFilter = keyof typeof MARKET_CAP_FILTERS;

/**
 * 根据市值筛选股票
 */
export function filterByMarketCap(stocks: StockInfo[], filter: MarketCapFilter): StockInfo[] {
  const threshold = MARKET_CAP_FILTERS[filter];
  if (threshold === 0) return stocks;
  return stocks.filter(s => s.marketCap > 0 && s.marketCap >= threshold);
}
// 兼容性别名
export const US_STOCKS = UNIQUE_STOCK_POOL;

/**
 * 时间级别标签
 */
export const TIMEFRAME_LABELS: Record<string, string> = {
  '1W': '周线',
  '1D': '日线',
  '4H': '4小时',
  '3H': '3小时',
  '2H': '2小时',
  '1H': '1小时',
  '30': '30分钟',
  '15': '15分钟',
};

/**
 * 市值筛选标签
 */
export const MARKET_CAP_LABELS: Record<string, string> = {
  all: '无限制',
  '1b': '10亿美元以上',
  '10b': '100亿美元以上',
  '50b': '500亿美元以上',
  '100b': '1000亿美元以上',
  '500b': '5000亿美元以上',
};

// ============================================================
// 市値分类（6级：微盘/小盘/中盘/大盘/超大盘/独角兽）
// ============================================================
export type MarketCapTier = 'unicorn' | 'mega' | 'large' | 'mid' | 'small' | 'micro';
/**
 * 独角兽：市値 >= 5000亿美元
 * 超大盘：市値 1000-5000亿美元
 * 大盘股：市値 500-1000亿美元
 * 中盘股：市値 100-500亿美元
 * 小盘股：市値 10-100亿美元
 * 微盘股：市値 0-10亿美元
 */
export function getMarketCapTier(marketCap: number): MarketCapTier {
  if (marketCap >= 5000) return 'unicorn';
  if (marketCap >= 1000) return 'mega';
  if (marketCap >= 500) return 'large';
  if (marketCap >= 100) return 'mid';
  if (marketCap >= 10) return 'small';
  return 'micro';
}
export const MARKET_CAP_TIER_LABELS: Record<MarketCapTier, string> = {
  unicorn: '独角兽 (5000亿+)',
  mega: '超大盘 (1000-5000亿)',
  large: '大盘股 (500-1000亿)',
  mid: '中盘股 (100-500亿)',
  small: '小盘股 (10-100亿)',
  micro: '微盘股 (0-10亿)',
};

// ============================================================
// 行业中文标签
// ============================================================
export const SECTOR_LABELS: Record<StockSector, string> = {
  AI: 'AI人工智能',
  Semiconductor: '半导体芯片',
  Bitcoin: '比特币/加密',
  EV: '电动汽车',
  Quantum: '量子计算',
  Storage: '存储/数据中心',
  RareEarth: '稀土/材料',
  Cloud: '云计算/SaaS',
  Fintech: '金融科技',
  Energy: '能源/油气',
  Healthcare: '医疗健康',
  Retail: '零售/消费',
  Tech: '科技',
  ETF: 'ETF指数基金',
  Finance: '金融/银行',
  Defense: '国防/军工',
  Industrial: '工业/制造',
  Biotech: '生物科技',
  Consumer: '消费品',
  Media: '媒体/娱乐',
  China: '中概股',
  Robotics: '机器人/自动化',
  SpaceTech: '航天/太空',
  Other: '其他',
};

// ============================================================
// 多维筛选函数
// ============================================================
export interface StockFilterOptions {
  sectors?: StockSector[];
  marketCapTiers?: MarketCapTier[];
  customSymbols?: string[];
  searchQuery?: string;
}

export function filterStocks(stocks: StockInfo[], options: StockFilterOptions): StockInfo[] {
  let result = [...stocks];
  if (options.customSymbols && options.customSymbols.length > 0) {
    const symbolSet = new Set(options.customSymbols.map(s => s.toUpperCase()));
    return result.filter(s => symbolSet.has(s.symbol));
  }
  if (options.sectors && options.sectors.length > 0) {
    const sectorSet = new Set(options.sectors);
    result = result.filter(s => s.sectors.some(sec => sectorSet.has(sec)));
  }
  if (options.marketCapTiers && options.marketCapTiers.length > 0) {
    const tierSet = new Set(options.marketCapTiers);
    result = result.filter(s => tierSet.has(getMarketCapTier(s.marketCap)));
  }
  if (options.searchQuery && options.searchQuery.trim()) {
    const q = options.searchQuery.trim().toLowerCase();
    result = result.filter(s =>
      s.symbol.toLowerCase().includes(q) || s.name.toLowerCase().includes(q)
    );
  }
  return result;
}

export function getSectorStats(stocks: StockInfo[]): Partial<Record<StockSector, number>> {
  const stats: Partial<Record<StockSector, number>> = {};
  for (const stock of stocks) {
    for (const sector of stock.sectors) {
      stats[sector] = (stats[sector] || 0) + 1;
    }
  }
  return stats;
}

export function getMarketCapTierStats(stocks: StockInfo[]): Record<MarketCapTier, number> {
  const stats: Record<MarketCapTier, number> = { unicorn: 0, mega: 0, large: 0, mid: 0, small: 0, micro: 0 };
  for (const stock of stocks) {
    stats[getMarketCapTier(stock.marketCap)]++;
  }
  return stats;
}
